"""Sharper's public package interface."""

from sharper.analysis import (
    CategoricalAnalysis,
    CorrelationAnalysis,
    GroupComparison,
    NumericAnalysis,
    OutlierAnalysis,
    TargetAnalysis,
    analyze_categorical_features,
    analyze_numeric_features,
    analyze_target_relationships,
    compare_groups,
    compute_correlations,
    detect_outliers,
)
from sharper.data_audit import (
    ColumnAuditRule,
    DataAuditConfig,
    DataAuditResult,
    DataAuditRoles,
    audit_data_quality,
)
from sharper.decision_strategy import (
    DecisionConstraint,
    DecisionRule,
    DecisionStrategyConfig,
    DecisionStrategyResult,
    StrategyCondition,
    simulate_decision_strategy,
)
from sharper.evaluation import (
    ClassificationEvaluation,
    RegressionEvaluation,
    evaluate_classifier,
    evaluate_model,
    evaluate_regressor,
)
from sharper.features import (
    FeatureDerivationResult,
    FeatureSuggestion,
    FeatureSuggestionReport,
    derive_features,
    suggest_feature_derivations,
)
from sharper.io import load_csv, load_excel
from sharper.lifecycle_monitoring import (
    EarlyWarningRule,
    LifecycleMonitoringConfig,
    LifecycleMonitoringResult,
    LifecycleState,
    MonitoringCondition,
    WarningScenario,
    monitor_lifecycle,
)
from sharper.model_governance import (
    GovernanceAttributionEvidence,
    GovernanceCandidate,
    GovernanceCriterion,
    GovernanceEvidenceRef,
    GovernanceExplanation,
    GovernanceMetadata,
    GovernancePerformanceEvidence,
    GovernancePolicy,
    GovernancePredictionProfile,
    GovernanceResult,
    evaluate_governance,
)
from sharper.modeling import (
    RegressionTrainingResult,
    TrainingResult,
    train_classifier,
    train_regressor,
)
from sharper.quality import QualityIssue, QualityReport, check_data_quality
from sharper.reporting import ReportArtifact, generate_analysis_report
from sharper.risk_validation import (
    BinaryRiskValidationConfig,
    BinaryRiskValidationResult,
    ExternalRiskPredictions,
    validate_binary_risk,
)
from sharper.schema import ColumnSchema, SchemaReport, TargetCandidate, infer_schema
from sharper.summary import DataFrameSummary, summarize_dataframe
from sharper.v02_reporting import generate_v02_report
from sharper.v02_workflow import (
    V02AuditRequest,
    V02GovernanceRequest,
    V02PostLoanRequest,
    V02PreLoanRequest,
    V02ScoreValidationRequest,
    V02WorkflowRequest,
    V02WorkflowResult,
    run_v02_workflow,
)
from sharper.visualization import (
    PlotCollection,
    PlotResult,
    plot_binary_risk_validation,
    plot_classification_evaluation,
    plot_correlations,
    plot_distributions,
    plot_group_comparison,
    plot_missingness,
    plot_model_governance,
    plot_outliers,
    plot_regression_evaluation,
    plot_target_relationships,
)
from sharper.workflow import AnalysisRun, run_analysis

__version__ = "0.2.0"

__all__ = [
    "__version__",
    "load_csv",
    "load_excel",
    "ColumnSchema",
    "TargetCandidate",
    "SchemaReport",
    "infer_schema",
    "DataFrameSummary",
    "summarize_dataframe",
    "QualityIssue",
    "QualityReport",
    "check_data_quality",
    "AnalysisRun",
    "run_analysis",
    "ReportArtifact",
    "generate_analysis_report",
    "NumericAnalysis",
    "CategoricalAnalysis",
    "CorrelationAnalysis",
    "OutlierAnalysis",
    "analyze_numeric_features",
    "analyze_categorical_features",
    "compute_correlations",
    "detect_outliers",
    "GroupComparison",
    "TargetAnalysis",
    "compare_groups",
    "analyze_target_relationships",
    "FeatureSuggestion",
    "FeatureSuggestionReport",
    "FeatureDerivationResult",
    "suggest_feature_derivations",
    "derive_features",
    "TrainingResult",
    "train_classifier",
    "RegressionTrainingResult",
    "train_regressor",
    "ClassificationEvaluation",
    "evaluate_classifier",
    "RegressionEvaluation",
    "evaluate_regressor",
    "evaluate_model",
    "PlotResult",
    "PlotCollection",
    "plot_distributions",
    "plot_missingness",
    "plot_correlations",
    "plot_outliers",
    "plot_group_comparison",
    "plot_target_relationships",
    "plot_classification_evaluation",
    "plot_regression_evaluation",
    "BinaryRiskValidationConfig",
    "ExternalRiskPredictions",
    "BinaryRiskValidationResult",
    "validate_binary_risk",
    "plot_binary_risk_validation",
    "DataAuditRoles",
    "ColumnAuditRule",
    "DataAuditConfig",
    "DataAuditResult",
    "audit_data_quality",
    "StrategyCondition",
    "DecisionRule",
    "DecisionConstraint",
    "DecisionStrategyConfig",
    "DecisionStrategyResult",
    "simulate_decision_strategy",
    "MonitoringCondition",
    "EarlyWarningRule",
    "WarningScenario",
    "LifecycleState",
    "LifecycleMonitoringConfig",
    "LifecycleMonitoringResult",
    "monitor_lifecycle",
    "GovernanceEvidenceRef",
    "GovernanceCandidate",
    "GovernanceCriterion",
    "GovernanceExplanation",
    "GovernanceAttributionEvidence",
    "GovernancePredictionProfile",
    "GovernancePerformanceEvidence",
    "GovernanceMetadata",
    "GovernancePolicy",
    "GovernanceResult",
    "evaluate_governance",
    "plot_model_governance",
    "V02ScoreValidationRequest",
    "V02AuditRequest",
    "V02PreLoanRequest",
    "V02PostLoanRequest",
    "V02GovernanceRequest",
    "V02WorkflowRequest",
    "V02WorkflowResult",
    "run_v02_workflow",
    "generate_v02_report",
]
